/* eslint-disable react-hooks/exhaustive-deps */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\mars.glb -T --shadows 
Files: .\public\models\mars.glb [23.83MB] > C:\Users\Mahendra\Desktop\portfolio\tic-tac-toe\mars-transformed.glb [560.33KB] (98%)
Author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-156a95dfec244e07a3ae423f579ffb05
Title: Mars
*/

import React, { useEffect, useRef } from 'react'
import { DragControls, OrbitControls, Sparkles, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { useSpring, animated, config } from '@react-spring/three'
import { useDrag } from 'react-use-gesture'

export function MarsModel() {
  const rotationRef = useRef(null)

  const [spring, api] = useSpring(()=> (
    {
      rotation: [0, 0, 0],
      config: config.gentle
    }
  ))

  const bind = useDrag(({ offset: [x, y] }) => {
    api.start({ rotation: [y / 100, x / 100, 0] });
    rotationRef.current.rotation.x = y / 1000
    rotationRef.current.rotation.y = x / 1000
  });
  
  useGSAP(()=>{

    const tl = gsap.timeline()
    tl.from(rotationRef.current.scale, {
      duration: 2.5,
      x: 0.5,
      y: 0.5,
      z: 0.5
    })

    tl.fromTo(rotationRef.current.rotation, {
      y: -3,
    }, {
      y: 0.5,
      duration: 3,
      ease: "power1.out"
    }, "<")
  }, [rotationRef.current])

  useFrame((state, delta)=> {
    if (rotationRef.current) {
      rotationRef.current.rotation.y += delta / 20
    }
  })
  
  const { nodes, materials } = useGLTF('./models/mars-transformed.glb')
  return (
    <>
      <group dispose={null} position={[0, -1, window.innerWidth < 500 ? -1 : 1]} ref={rotationRef}>
        <animated.mesh {...bind()} rotation={spring.rotation} castShadow receiveShadow geometry={nodes.Mars_LOD0_MarsLOD1_0.geometry} material={materials.MarsLOD1} position={[0, 2.5, 0]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </>
  )
}

useGLTF.preload('./models/mars-transformed.glb')
